### ISSUE TITLE
Custom Message for Request SMS

### ISSUE THREAD

**Issue by sivailangos** [authy/authy-java#23]
How do I set custom message to send SMS, I found something here https://docs.authy.com/phone_verification.html#phone-verification-api to setup custom message.

**Comment by fayimora** [comment]
@sivailangos from the docs 

> If you need to overwrite the default message sent to the user you can use the custom_message parameter. This is not enabled by default and you must contact support@authy.com to request this parameter. Once enabled, it will allow you to send virtually any message you'd like in over 160 languages for SMS and 26 for automated voice calls. However you must manage the localization of the messages sent and you need to insert the Authy code into your message using the macro show in the parameter below.
