### ISSUE TITLE
Get same code in JAVA, like I receive code in Authy application on phone.

### ISSUE THREAD

**Issue by GoldenScrew** [authy/authy-java#24]
Hello, really need help, I am novice in programming, also my English is bad and I have big problem in understanding (in russian language no information about it). 
But I need receive same code (SoftToken), like I receive in my application Authy on phone.
Is authy-java for me? If so, where I should find this **your-api-key**?
I want solve this: http://stackoverflow.com/questions/39151880/get-same-two-factor-code-like-i-received-in-my-app-authy-in-java

Also, when I try use authy-java with code:

```
AuthyApiClient client = new AuthyApiClient("INVALID_API_KEY", "https://api.authy.com/");
System.out.println(client.getUsers().toString());
```

I haven't error, but my api_key is invalid, why?

**Comment by TechFreak** [comment]
Hi @GoldenScrew please check our documentation page https://www.twilio.com/docs/api/authy/authy-totp to understand how to authenticate and get a valid API key
