### ISSUE TITLE
Unable to integrate the jar file into my Android application

### ISSUE THREAD

**Issue by mfissehaye** [authy/authy-java#25]
I am getting the following error when I copy the jar file in the dist/ directory and past it into my libs folder in my android project.
I am building my android project using java 1.8 
Please help

Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing org/json/CDL.class
Error:1 error; aborting
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 1

**Comment by yuniersoad** [comment]
please take a look at https://github.com/authy/authy-java/issues/22
