### ISSUE TITLE
Maven dependency update

### ISSUE THREAD

**Issue by nfedyk** [authy/authy-java#34]
Current version in Maven repository is 1.2.0 and it doesn't have call request capabilities. Can someone please update the artifact on maven?

**Comment by bmudda** [comment]
+1

**Comment by TechFreak** [comment]
We have just released v1.3.0 of the library with call request capabilities.

**Comment by nfedyk** [comment]
Where can I find the release? [Maven](https://mvnrepository.com/artifact/com.authy/authy-java) doesn't have 1.3.0

**Comment by TechFreak** [comment]
Probably still indexing, but we see it already here:
https://search.maven.org/#artifactdetails%7Ccom.authy%7Cauthy-java%7C1.3.0%7Cjar
and here http://repo1.maven.org/maven2/com/authy/authy-java/1.3.0/
