### ISSUE TITLE
Example webapp broken

### ISSUE THREAD

**Issue by jnovotny** [authy/authy-java#43]
Hi,

I'm following the guide here https://www.twilio.com/docs/tutorials/two-factor-authentication-java-servlets. First are these projects related? I'm trying to find a sample wbapp to try first.

However, in the README I do mvn compile jetty:run but nothing happens, and I see no listener socket set up on 8080.

Thanks, Jason

**Comment by TechFreak** [comment]
Hi @jnovotny the sample web app is at https://github.com/TwilioDevEd/authy2fa-servlets, that sample uses this client library to interact with the 2FA API
